INSERT INTO `pep_notice_template`(`ID`, `CREATE_TIME`, `CREATE_USER_ID`, `LAST_MODIFY_TIME`, `LAST_MODIFY_USER_ID`, `ENABLE`, `CODE`, `NAME`, `TITLE`, `TEMPLATE`, `DESCRIPTION`, `TYPE`, `CATELOG`) VALUES ('idEndNotice', '2018-08-08 00:00:00.000', 'PEP', '2018-08-08 00:00:00.000', 'PEP', 'Y', 'EndCode', 'EndCode', '流程完结', '您的【{processDefinitionName}】已完成，详情请在【发起历史】中查看。', '1', 'NOTICE_CHANNEL;EMAIL', 'NOTICE_BUSINESS;EndNotice');
INSERT INTO `pep_notice_template`(`ID`, `CREATE_TIME`, `CREATE_USER_ID`, `LAST_MODIFY_TIME`, `LAST_MODIFY_USER_ID`, `ENABLE`, `CODE`, `NAME`, `TITLE`, `TEMPLATE`, `DESCRIPTION`, `TYPE`, `CATELOG`) VALUES ('idEndNotice2', '2018-08-08 00:00:00.000', 'PEP', '2018-08-08 00:00:00.000', 'PEP', 'Y', 'EndCode', 'EndNotice', '您有一条已办消息', '您的{processDefinitionName}已完成', '2', 'NOTICE_CHANNEL;PUSH', 'NOTICE_BUSINESS;EndNotice');
INSERT INTO `pep_notice_template`(`ID`, `CREATE_TIME`, `CREATE_USER_ID`, `LAST_MODIFY_TIME`, `LAST_MODIFY_USER_ID`, `ENABLE`, `CODE`, `NAME`, `TITLE`, `TEMPLATE`, `DESCRIPTION`, `TYPE`, `CATELOG`) VALUES ('idEntryTaskAssignee', '2018-08-13 00:00:00.000', 'PEP', '2018-08-13 00:00:00.000', 'PEP', 'Y', 'EntryTaskAssignee', 'EntryTaskAssignee', '流程待办', '【{initiatorName}】发起的【{name}】的【{processDefinitionName}】已经到达您的代办，请您处理【<a href={pageurl}>{taskName}</a>】。', '1', 'NOTICE_CHANNEL;EMAIL', 'NOTICE_BUSINESS;EndNotice');
INSERT INTO `pep_notice_template`(`ID`, `CREATE_TIME`, `CREATE_USER_ID`, `LAST_MODIFY_TIME`, `LAST_MODIFY_USER_ID`, `ENABLE`, `CODE`, `NAME`, `TITLE`, `TEMPLATE`, `DESCRIPTION`, `TYPE`, `CATELOG`) VALUES ('idEntryTaskAssignee2', '2018-08-13 00:00:00.000', 'PEP', '2018-08-13 00:00:00.000', 'PEP', 'Y', 'EntryTaskAssignee', 'EntryTaskAssignee', '您有一条新的待办消息', '{name}的{processDefinitionName}', '2', 'NOTICE_CHANNEL;PUSH', 'NOTICE_BUSINESS;EndNotice');
INSERT INTO `pep_notice_template`(`ID`, `CREATE_TIME`, `CREATE_USER_ID`, `LAST_MODIFY_TIME`, `LAST_MODIFY_USER_ID`, `ENABLE`, `CODE`, `NAME`, `TITLE`, `TEMPLATE`, `DESCRIPTION`, `TYPE`, `CATELOG`) VALUES ('idTaskAssignee', '2018-08-08 00:00:00.000', 'PEP', '2018-08-08 00:00:00.000', 'PEP', 'Y', 'TaskAssignee', 'TaskAssignee', '流程待办', '【{initiatorName}】发起的【{processDefinitionName}】已经到达您的代办，请您处理【<a href={pageurl}>{taskName}</a>】。', '1', 'NOTICE_CHANNEL;EMAIL', 'NOTICE_BUSINESS;EndNotice');
INSERT INTO `pep_notice_template`(`ID`, `CREATE_TIME`, `CREATE_USER_ID`, `LAST_MODIFY_TIME`, `LAST_MODIFY_USER_ID`, `ENABLE`, `CODE`, `NAME`, `TITLE`, `TEMPLATE`, `DESCRIPTION`, `TYPE`, `CATELOG`) VALUES ('idTaskAssignee2', '2018-08-08 00:00:00.000', 'PEP', '2018-08-08 00:00:00.000', 'PEP', 'Y', 'TaskAssignee', 'TaskAssignee', '您有一条新的待办消息', '{initiatorName}的{processDefinitionName}', '2', 'NOTICE_CHANNEL;PUSH', 'NOTICE_BUSINESS;EndNotice');
INSERT INTO `pep_notice_template`(`ID`, `CREATE_TIME`, `CREATE_USER_ID`, `LAST_MODIFY_TIME`, `LAST_MODIFY_USER_ID`, `ENABLE`, `CODE`, `NAME`, `TITLE`, `TEMPLATE`, `DESCRIPTION`, `TYPE`, `CATELOG`) VALUES ('idTaskAssigneeEntry', '2018-08-08 00:00:00.000', 'PEP', '2018-08-08 00:00:00.000', 'PEP', 'Y', 'TaskAssigneeEntry', 'TaskAssigneeEntry', '流程待办', '【{initiatorName}】发起的【{processDefinitionName}】已经到达您的代办，请您处理【<a href={pageurl}>{taskName}</a>】。', '1', 'NOTICE_CHANNEL;EMAIL', 'NOTICE_BUSINESS;TaskAssigneeEntry');
INSERT INTO `pep_notice_template`(`ID`, `CREATE_TIME`, `CREATE_USER_ID`, `LAST_MODIFY_TIME`, `LAST_MODIFY_USER_ID`, `ENABLE`, `CODE`, `NAME`, `TITLE`, `TEMPLATE`, `DESCRIPTION`, `TYPE`, `CATELOG`) VALUES ('idTaskAssigneeEntry2', '2018-08-08 00:00:00.000', 'PEP', '2018-08-08 00:00:00.000', 'PEP', 'Y', 'TaskAssigneeEntry', 'TaskAssigneeEntry', '您有一条新的待办消息', '{initiatorName}的{processDefinitionName}', '2', 'NOTICE_CHANNEL;PUSH', 'NOTICE_BUSINESS;TaskAssigneeEntry');
INSERT INTO pep_auth_users (id, username, password, superuser, pep_dtype, name, phone, email, enable) VALUES ('test1', 't1', 'pwd', 'Y', 'UserEntity', 'c', '12345678901', 'test1@test.com', 'Y');


