pep-mysql:
  image: mysql
  volumes:
    - ./mysql/data:/var/lib/mysql
    - ./mysql/conf:/etc/mysql/conf.d
    - ./mysql/init:/docker-entrypoint-initdb.d
  environment:
    - MYSQL_ROOT_PASSWORD=Proper123
    - MYSQL_DATABASE=pep
    - MYSQL_USER=pep
    - MYSQL_PASSWORD=pep
# Could deploy mongo shard cluster using https://github.com/propersoft-cn/docker-mongo-shard-cluster
pep-mongo:
  image: mongo:3.6.5
  entrypoint: /code/devops/current/mongoEp.sh
  volumes:
    - ./mongo/data:/data/db
    - ./mongo/devops/:/code/devops/current/
pep-redis:
  image: redis
  volumes:
    - ./redis/data:/data
    - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  command: redis-server /usr/local/etc/redis/redis.conf --appendonly yes
pep-server:
  image: propersoft/docker-tomcat:7.0.82-jre8
  volumes:
    - ./tomcat/webapps:/usr/local/tomcat/webapps
    - ./tomcat/logs:/usr/local/tomcat/logs
  links:
    - pep-mongo:mongo
    - pep-mysql:mysql
    - pep-redis:redis
  environment:
    - JAVA_OPTS=-server -Xms512m -Xmx4096m
pep-nginx:
  image: nginx
  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  links:
    - pep-server:pep
  ports:
    - "8080:80"
