INSERT INTO PEP_PUSH_CHANNEL (ID, CHANNEL_NAME, CHANNEL_DESC, SECRET_KEY,MAX_SEND_COUNT, MSG_SAVE_DAYS) VALUES ('test1', 'MobileOADev', '掌上办公开发', 'aaa','5','3');
INSERT INTO PEP_PUSH_CHANNEL (ID, CHANNEL_NAME, CHANNEL_DESC, SECRET_KEY,MAX_SEND_COUNT, MSG_SAVE_DAYS) VALUES ('test2', 'MobileOAPr', '掌上办公普日', 'bbb','5','3');
INSERT INTO PEP_PUSH_CHANNEL (ID, CHANNEL_NAME, CHANNEL_DESC , SECRET_KEY,MAX_SEND_COUNT, MSG_SAVE_DAYS) VALUES ('test3', 'MobileOADemo', '掌上办公演示', 'ccc','5','3');
INSERT INTO PEP_PUSH_CHANNEL (ID, CHANNEL_NAME, CHANNEL_DESC , SECRET_KEY,MAX_SEND_COUNT, MSG_SAVE_DAYS) VALUES ('test4', 'test', '测试', 'ddd','5','3');
