-- 数据字典model部署状态
INSERT INTO PEP_SYS_DATA_DIC (ID, DD_CATALOG, DD_CODE, DD_NAME, DD_ORDER, IS_DEFAULT) VALUES ('test1', 'ModelStatus', 'DEPLOYED', '已部署', 0, 'N');
INSERT INTO PEP_SYS_DATA_DIC (ID, DD_CATALOG, DD_CODE, DD_NAME, DD_ORDER, IS_DEFAULT) VALUES ('test2', 'ModelStatus', 'UN_DEPLOYED', '未部署', 1, 'Y');
INSERT INTO PEP_SYS_DATA_DIC (ID, DD_CATALOG, DD_CODE, DD_NAME, DD_ORDER, IS_DEFAULT) VALUES ('test3', 'ModelStatus', 'NO_NAME', '', 1, 'N');
