-- 数据字典model部署状态
INSERT INTO PEP_SYS_DATA_DIC (ID, DD_CATALOG, DD_CODE, DD_NAME, DD_ORDER, IS_DEFAULT) VALUES ('test1', 'PEP_PUSH_CHANNEL_TYPE', 'xiaomi', '小米', 0, 'N');
INSERT INTO PEP_SYS_DATA_DIC (ID, DD_CATALOG, DD_CODE, DD_NAME, DD_ORDER, IS_DEFAULT) VALUES ('test2', 'PEP_PUSH_CHANNEL_TYPE', 'huawei', '华为', 1, 'N');
INSERT INTO PEP_SYS_DATA_DIC (ID, DD_CATALOG, DD_CODE, DD_NAME, DD_ORDER, IS_DEFAULT) VALUES ('test3', 'PEP_PUSH_CHANNEL_TYPE', 'apns', '苹果', 2, 'N');
